# Generated by Django 2.1.7 on 2019-02-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, max_length=20)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('raw', models.CharField(max_length=200)),
                ('formatted', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accessibility', models.NullBooleanField()),
                ('price_per_week', models.FloatField(blank=True, null=True)),
                ('max_guests', models.IntegerField(blank=True, null=True)),
                ('num_bathrooms', models.IntegerField(blank=True, null=True)),
                ('air_conditioning', models.NullBooleanField()),
                ('wifi', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='locality.Locality')),
            ],
        ),
    ]
